name: di_container
description: DI Container is a lightweight DI library inspired by .NET Service Collection
version: 0.1.0
repository: https://github.com/yoeden/flutter_di_container

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
