name: benchmarks
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  benchmark_harness: any
  kiwi: ^4.1.0
  get_it: ^7.6.4
  injector: ^3.0.0
  ioc_container: ^1.0.9
  services:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
